steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia-south1-docker.pkg.dev/$PROJECT_ID/tc-agent/supplier-tc-agent:$COMMIT_SHA
      - .
images:
  - asia-south1-docker.pkg.dev/$PROJECT_ID/tc-agent/supplier-tc-agent:$COMMIT_SHA
